

export const countries = [
    { value: "MX", name: "Mexicana" },
    { value: "US", name: "Estadounidense" },
    { value: "GT", name: "Guatemalteco" },
    { value: "CR", name: "Costarricense" },
    { value: "PR", name: "Puerto Rico" },
    { value: "SV", name: "Salvadoreño" },
    { value: "NI", name: "Nicaragua" },
    { value: "AF", name: "Afgana" },
    { value: "AX", name: "Aland Islands" },
    { value: "AL", name: "Albania" },
    { value: "DE", name: "Alemana" },
    { value: "AD", name: "Andorrana" },
    { value: "AO", name: "Angolesa" },
    { value: "AI", name: "Anguila" },
    { value: "AG", name: "Antigua y Barbuda" },
    { value: "SA", name: "Árabe" },
    { value: "DZ", name: "Argeliana" },
    { value: "AR", name: "Argentina" },
    { value: "AM", name: "Armenia" },
    { value: "AU", name: "Australiana" },
    { value: "AT", name: "Austriaca" },
    { value: "AZ", name: "Azerbaiyán" },
    { value: "AW", name: "(No usar) Azerbaiyán" },
    { value: "BS", name: "Bahameña" },
    { value: "BD", name: "Bangladés" },
    { value: "BB", name: "Barbados" },
    { value: "BE", name: "Belga" },
    { value: "BZ", name: "Beliceña" },
    { value: "BJ", name: "Benin" },
    { value: "BH", name: "Beréin" },
    { value: "BM", name: "Bermudas" },
    { value: "BY", name: "Bielorrusia" },
    { value: "MM", name: "Birmana" },
    { value: "BO", name: "Boliviana" },
    { value: "BQ", name: "Bonaire" },
    { value: "BA", name: "Botswanesa" },
    { value: "BW", name: "Botswana" },
    { value: "BR", name: "Brasileña" },
    { value: "BN", name: "Brunéi" },
    { value: "BG", name: "Bulgara" },
    { value: "BF", name: "Burkina Faso" },
    { value: "BI", name: "Burundesa" },
    { value: "BT", name: "Bután" },
    { value: "CV", name: "Cabo Verde" },
    { value: "KY", name: "Caimán, Islas" },
    { value: "KH", name: "Camboyana" },
    { value: "CM", name: "Camerunesa" },
    { value: "CA", name: "Canadiense" },
    { value: "QA", name: "Catar" },
    { value: "CF", name: "Centro Africana" },
    { value: "TD", name: "Chadiana" },
    { value: "CZ", name: "Checoslovaca" },
    { value: "CL", name: "Chilena" },
    { value: "CN", name: "China" },
    { value: "CY", name: "Chipriota" },
    { value: "CC", name: "Cocos, Islas" },
    { value: "CO", name: "Colombiana" },
    { value: "KM", name: "Comorense" },
    { value: "CG", name: "Congolesa" },
    { value: "CD", name: "Congolesa" },
    { value: "CK", name: "Cook, Islas" },
    { value: "KP", name: "Corea del Norte" },
    { value: "KR", name: "Corea del Sur" },
    { value: "CI", name: "Costa de Marfil" },
    { value: "HR", name: "Croacia" },
    { value: "CU", name: "Cubana" },
    { value: "CW", name: "Curazao" },
    { value: "DK", name: "Danesa" },
    { value: "DM", name: "Dominicana" },
    { value: "EC", name: "Ecuador" },
    { value: "EG", name: "Egipcia" },
    { value: "SV", name: "Salvadoreño" },
    { value: "AE", name: "Emiratos Árabes Unidos" },
    { value: "ER", name: "Eritrea" },
    { value: "SK", name: "Eslovaca" },
    { value: "SI", name: "Eslovenia" },
    { value: "ES", name: "Española" },
    { value: "EE", name: "Estonia" },
    { value: "ET", name: "Etiope" },
    { value: "FO", name: "Feroe, Islas" },
    { value: "PH", name: "Filipina" },
    { value: "FI", name: "Finlandesa" },
    { value: "FJ", name: "Fijiana" },
    { value: "FR", name: "Francesa" },
    { value: "GA", name: "Gabonesa" },
    { value: "GM", name: "Gambiana" },
    { value: "GE", name: "Georgia" },
    { value: "GH", name: "Ghanata" },
    { value: "GI", name: "Gibraltar" },
    { value: "GR", name: "Griega" },
    { value: "GD", name: "Granadina" },
    { value: "GL", name: "Groenlandia" },
    { value: "GP", name: "Guadalupe" },
    { value: "GU", name: "Guam" },
    { value: "GT", name: "Guatemalteca" },
    { value: "GG", name: "Guernsey" },
    { value: "GQ", name: "Guinea Ecuatorial" },
    { value: "GN", name: "Guinea" },
    { value: "GW", name: "Guinea" },
    { value: "GF", name: "Guyanesa" },
    { value: "GY", name: "Guyanesa" },
    { value: "HT", name: "Haitiana" },
    { value: "HN", name: "Hondureña" },
    { value: "HK", name: "Hong Kong" },
    { value: "HU", name: "Hungara" },
    { value: "IN", name: "Hindu" },
    { value: "ID", name: "Indonesa" },
    { value: "IQ", name: "Iraqui" },
    { value: "IR", name: "Irani" },
    { value: "IE", name: "Irlandesa" },
    { value: "IS", name: "Islandesa" },
    { value: "IL", name: "Israeli" },
    { value: "IT", name: "Italiana" },
    { value: "JM", name: "Jamaiquina" },
    { value: "JP", name: "Japonesa" },
    { value: "JE", name: "Jersey" },
    { value: "JO", name: "Jordana" },
    { value: "KZ", name: "Kazajistán" },
    { value: "KE", name: "Keniana" },
    { value: "KG", name: "Kirguistan" },
    { value: "KI", name: "Kiribati" },
    { value: "KW", name: "Kuwaiti" },
    { value: "LA", name: "Laosiana" },
    { value: "LS", name: "Lesothense" },
    { value: "LV", name: "Letonia" },
    { value: "LB", name: "Libanesa" },
    { value: "LR", name: "Liberiana" },
    { value: "LY", name: "Libia" },
    { value: "LI", name: "Liechtenstense" },
    { value: "LT", name: "Lituania" },
    { value: "LU", name: "Luxemburguesa" },
    { value: "MO", name: "Macao" },
    { value: "MK", name: "Macedonia" },
    { value: "MG", name: "Madagascar" },
    { value: "MY", name: "Malasia" },
    { value: "MV", name: "Maldiva" },
    { value: "ML", name: "Maliense" },
    { value: "MT", name: "Maltesa" },
    { value: "MW", name: "Malui" },
    { value: "FK", name: "Malvinas, Islas" },
    { value: "IM", name: "Man, Isla de" },
    { value: "MP", name: "Marianas del Norte, Islas" },
    { value: "MA", name: "Marroqui" },
    { value: "MH", name: "Marshall, Islas" },
    { value: "MR", name: "Martinica" },
    { value: "MQ", name: "Martinique" },
    { value: "MU", name: "Mauriciana" },
    { value: "YT", name: "Mayotte" },
    { value: "FM", name: "Micronecia" },
    { value: "MD", name: "Moldovia" },
    { value: "MC", name: "Monegasca" },
    { value: "MN", name: "Mongolesa" },
    { value: "ME", name: "Montenegro" },
    { value: "MS", name: "Montserrat" },
    { value: "MZ", name: "Mozambiqueña" },
    { value: "NA", name: "Namibiana" },
    { value: "NR", name: "Nauruana" },
    { value: "CX", name: "Navidad, Isla de" },
    { value: "NP", name: "Nepalesa" },
    { value: "NI", name: "Nicaraguense" },
    { value: "NE", name: "Nigerina" },
    { value: "NG", name: "Nigeriana" },
    { value: "NU", name: "Niue" },
    { value: "NF", name: "Norfolk, Islas" },
    { value: "NO", name: "Noruega" },
    { value: "NC", name: "Nueva Caledonia" },
    { value: "NZ", name: "Nueva Zelanda" },
    { value: "OM", name: "Omanesa" },
    { value: "NL", name: "Holanda" },
    { value: "PK", name: "Pakistani" },
    { value: "PW", name: "Palaos" },
    { value: "PS", name: "Palestina" },
    { value: "PA", name: "Panameña" },
    { value: "PG", name: "Papuense" },
    { value: "PY", name: "Paraguaya" },
    { value: "PE", name: "Peruana" },
    { value: "PF", name: "Polinesia Francesa" },
    { value: "PL", name: "Polonia" },
    { value: "PT", name: "Portuguesa" },
    { value: "GB", name: "Inglesa" },
    { value: "DO", name: "Dominicana" },
    { value: "RE", name: "Reunion" },
    { value: "RW", name: "Rwandesa" },
    { value: "RO", name: "Rumana" },
    { value: "RU", name: "Rusa" },
    { value: "SB", name: "Salomonesa" },
    { value: "AS", name: "Samao Americana" },
    { value: "WS", name: "Samoana" },
    { value: "BL", name: "San Bartolomé" },
    { value: "SM", name: "San Marino, Republic of" },
    { value: "MF", name: "San Martín" },
    { value: "SX", name: "San Martín" },
    { value: "VC", name: "San Vicente y las Granadinas" },
    { value: "LC", name: "Santa Lucía" },
    { value: "ST", name: "Santo Tomé y Príncipe" },
    { value: "SN", name: "Senegalesa" },
    { value: "RS", name: "Serbia" },
    { value: "SC", name: "Seychelles" },
    { value: "SL", name: "Sierra Leona" },
    { value: "SG", name: "Singaporense" },
    { value: "SY", name: "Siria" },
    { value: "SO", name: "Somali" },
    { value: "LK", name: "Sri Lanka" },
    { value: "SH", name: "St. Helena" },
    { value: "KN", name: "St. Kitts and Nevis" },
    { value: "PM", name: "St. Pierre and Miquelon" },
    { value: "SZ", name: "Suazilandia" },
    { value: "ZA", name: "Sudafricana" },
    { value: "SD", name: "Sudanesa" },
    { value: "SS", name: "Sudcoreana" },
    { value: "SE", name: "Sueca" },
    { value: "CH", name: "Suiza" },
    { value: "SR", name: "Surinamense" },
    { value: "SJ", name: "Svalbard &amp;amp; Jan Mayen Islands" },
    { value: "TH", name: "Tailandesa" },
    { value: "TW", name: "Taiwanesa" },
    { value: "TZ", name: "Tanzaniana" },
    { value: "TJ", name: "Tayikistán" },
    { value: "TL", name: "Timor Oriental" },
    { value: "TG", name: "Togolesa" },
    { value: "TO", name: "Tonga" },
    { value: "TT", name: "Trinitaria" },
    { value: "TN", name: "Tunecina" },
    { value: "TC", name: "Turcas y Caicos, Islas" },
    { value: "TM", name: "Turkmenistán" },
    { value: "TR", name: "Turca" },
    { value: "TV", name: "Tuvalu" },
    { value: "UA", name: "Ucrania" },
    { value: "UG", name: "Ugandesa" },
    { value: "UM", name: "United States Minor Outlying Islands" },
    { value: "UY", name: "Uruguaya" },
    { value: "UZ", name: "Uzbekistan" },
    { value: "VU", name: "Vanuatu" },
    { value: "VE", name: "Venezolana" },
    { value: "VN", name: "Vietnam" },
    { value: "VG", name: "Vírgenes Británicas, Islas" },
    { value: "VI", name: "Vírgenes de los Estados Unidos, Islas" },
    { value: "WF", name: "Wallis Y Futuna" },
    { value: "YE", name: "Yemeni" },
    { value: "DJ", name: "Yibuti" },
    { value: "ZM", name: "Zambia" },
    { value: "ZW", name: "Zimbabue" },
    { value: "ESC", name: "Escocia" },
    { value: "TRS", name: "Tierra Santa" },
    { value: "DUB", name: "Dubai" },
    { value: "PTR", name: "Petra" },
    { value: "TRS", name: "Tierra Santa" },
    { value: "EST", name: "Estambul" },
    { value: "QAT", name: "Qatar" },
    { value: "PB", name: "Países Bajos" }
];
